[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "btreefilereader"
version = "1.0"

[tool.poetry.dependencies]
python = ">=3.12.0, <4"
pandas = ">2.0"