[metadata]
reg_quotes = 2
trading_date = 8
bdi_id = 2
stock_id = 12
market_type = 3
company = 12
stock_specif = 10
forward_market_term_days = 3
currency = 4
open = 13
high = 13
low = 13
average = 13
close = 13
best_purchase = 13
best_sale = 13
nb_trades_stock = 5
nb_shares_stock = 18
volume = 18
price_or_amount = 13
price_or_amount_corr_ind = 1
maturity_date = 8
stock_quotation = 7
price_or_amount_points = 13
stock_isin_id = 12
stock_distr = 3

[markets]
cash = 10
exercise_call_option = 12
exercise_put_option = 13
auction = 17
fractional = 20
term = 30
future_with_retention_of_gain = 50
continuous_trading_future = 60
call_option = 70
put_option = 80

[indopc]
uss = 1
tjlp = 2
igpm = 8
urv = 9

[codbdi]
standard_lot = 1
sanctioned_by_bmfbovespa_regulations = 2
concordatarias = 3
extrajudicial_recovery = 4
judicial_recovery = 5
special_temporary_administration_regime = 6
rights_and_receipts = 7
intervention = 8
real_estate_funds = 9
thirteen = 10
cert_invest_tit_div_publica = 11
obligations = 12
private_bonds = 13
notes_bonds_public_securities = 14
exercise_of_stock_index_call_options = 15
exercise_of_stock_index_put_options = 16
thirty_four = 17
thirty_five = 18
thirty_six = 19
thirty_seven = 20
exercise_of_stock_call_options = 21
exercise_of_stock_put_options = 22
auction_of_non_quoted_stocks = 23
privatization_auction = 24
auction_of_economic_recovery_fund_espirito_santo = 25
auction = 26
finor_auction = 27
finam_auction = 28
fiset_auction = 29
auction_of_shares_in_arrears = 30
sales_by_judicial_order = 31
others = 32
swap_for_stocks = 33
target = 34
spot_market = 35
debentures_with_maturity_up_to_3_years = 36
debentures_with_maturity_over_3_years = 37
future_with_retention_of_gain = 38
future_market = 39
call_option_on_stock_index = 40
put_option_on_stock_index = 41
stock_call_option = 42
stock_put_option = 43
bovespafix = 44
soma_fix = 45
registered_spot_term = 46
fractional_market = 47
general_total = 48
